Implement Vec
TimDiekmann/alloc-wg pull request #2
Opened 2019-11-06 18:06 UTC by 95th

2019-11-06 18:59 UTC, 95th commented
@TimDiekmann some doc tests are failing. Do you want me to remove them?

2019-11-07 11:54 UTC, TimDiekmann requested changes
Nice work so far, thank you!

Let's try to fix the CI and merge this, then we can further extend the API. Let's also add feature flags for the API, which is currently unstable upstream (like mentioned in two review comments, but for the other methods as well). Do you know, why the equality checks are failing? Currently, there are no comparison traits implemented for an allocator awared vector, but the test shouldn't fail anyway.

Currently, methods like `shrink_to_fit` are only available for infallible allocators. We may want to add a `try_shrink_to_fit`, which does not bind `crate::Never` as allocation error. But this should be added in another PR, as this PR is big enough and hard to review anyway :wink:

2019-11-07 11:54 UTC, TimDiekmann commented on src/lib.rs
> +#[cfg(feature = "std")]
Why limiting to `std` here?
```suggestion
```

2019-11-07 11:54 UTC, TimDiekmann commented on src/vec.rs
> +        // unsafe { assume(!ptr.is_null()); }
Why commenting out this line? `ptr` Should always be non-null, as `RawVec` internally indirectly uses `NonNull`. This, btw. is the reason, why the `Lint`-Action failed :)
```suggestion
        unsafe { assume(!ptr.is_null()); }
```

2019-11-07 11:54 UTC, TimDiekmann commented on src/vec.rs
> +
Let's not keep this from the `alloc` crate and collapse the `else { if .. }` thing.

2019-11-07 11:54 UTC, TimDiekmann commented on src/vec.rs
> +
This is currently a nightly feature `vec_drain_as_slice`. Let's gate this behind a feature flag too.

2019-11-07 11:54 UTC, TimDiekmann commented on src/vec.rs
> +    pub fn drain_filter<F>(&mut self, filter: F) -> DrainFilter<'_, T, F, B>
This is currently a nightly feature `drain_filter`. Let's gate this behind a feature flag too.

2019-11-07 11:55 UTC, TimDiekmann commented
> @TimDiekmann some doc tests are failing. Do you want me to remove them?

I would have suggested to use `alloc_wg::Vec` in tests, but you already force-pushed this change :+1:

2019-11-07 12:16 UTC, TimDiekmann commented on src/vec.rs
> +
Let's not keep this from the alloc crate and collapse the else { if .. } thing.

2019-11-07 12:17 UTC, TimDiekmann commented on src/vec.rs
> +
Second time I tried to add a multiline comment, but it's not marking the correct lines. The affected lines are 2248 to 2265

2019-11-07 15:04 UTC, 95th commented
Thanks. There are still some failures.. I'll check after work.

2019-11-07 15:57 UTC, TimDiekmann commented
The windows build exits with the exit code `-1073740940` (heap corruption) in `shrink_to` and `shrink_to_fit`. This probably means, that `RawVec::try_shrink_to_fit` has a bug. I'll investigate this further when I'm back at home.

2019-11-08 12:26 UTC, TimDiekmann commented
As the tests with my PR on your repo work, I'll merge this and apply PR myself. Thanks again :slightly_smiling_face:

2019-11-08 12:26 UTC, merged